### ISSUE TITLE
No Configuration for Lava Lily Spawn rate?

### ISSUE THREAD

**Issue by Ghostrider231** [EwyBoy/Floating-Rails#2]
Hello, According to the source code posted here and in the mod; I've noticed that there is a config code for changing the lava lily spawn rate, but loading this mod doesn't create a config file for that? 

I've tested this out and tried to find the config file, but no anvil. 

Even tried a fresh empty config folder with only this mod and still no anvil. (I only see the typical forge config files and that's it)

- Minecraft Ver. 1.12.2, latest version of this mod.

**Comment by EwyBoy** [comment]
Yeah the src code on GitHub is outdated from the 1.7 version. I will fix it for the 1.12 version soon.

**Comment by EwyBoy** [comment]
It is fixed now in v2.0.2 https://minecraft.curseforge.com/projects/floating-rails/files/2649637
