### ISSUE TITLE
Broken item textures

### ISSUE THREAD

**Issue by ghost** [EwyBoy/Floating-Rails#3]
The Magma Lily has a broken texture in the inventory.

![2018-12-12_19 06 19](https://user-images.githubusercontent.com/17183816/49906763-31678f80-fe41-11e8-9e05-328e568a9670.png)

Forge : 2768
Floating Rails: 2.0.1

**Comment by EwyBoy** [comment]
thanks, I will try to get it fixed as soon as possible.

**Comment by EwyBoy** [comment]
Forge changed some stuff since my previous build that broke how itemblocks json file where formatted. It should be fixed in the latest build v2.0.2: https://minecraft.curseforge.com/projects/floating-rails/files/2649637
