### ISSUE TITLE
Magma lilies spawn in flowing lava

### ISSUE THREAD

**Issue by DefinitelyNotFred** [EwyBoy/Floating-Rails#4]
Not sure if this is a bug, a feature, or a compatibility issue. I just find it weird seeing the lilies float above the lava while I'm caving.

**Comment by EwyBoy** [comment]
Lava lilies are programmed to spawn on top of any lava pool found in natural world generation. Do they spawn on top of the lava or floating in mid air?

**Comment by DefinitelyNotFred** [comment]
They are spawning on top of flowing lava, so it looks like they are floating, but they are actually just sitting on the less than full block.

**Comment by EwyBoy** [comment]
Okey, I will try to get that fixed as fast as possible. Thanks for reporting

**Comment by DefinitelyNotFred** [comment]
So I created a new minecraft instance with no other mods this time and I've found one of the lilies I'm talking about. The seed is 1813504243948084945 and the coordinates are 114, 13,  949. There is another one at 74, 27, 1047.

Thank you for the quick response and the mod in the first place.

**Comment by EwyBoy** [comment]
Thanks for the bug report.
The should be resolved in the next build, 2.0.3-1.12.2.
Link: https://minecraft.curseforge.com/projects/floating-rails/files/2716813
