### ISSUE TITLE
Magma Lilies can be placed in flowing lava if right clicking against another block

### ISSUE THREAD

**Issue by DefinitelyNotFred** [EwyBoy/Floating-Rails#5]
It is necessary that there be a solid block to right click against. Simply right clicking the lava flow against air will do nothing.

https://imgur.com/a/3AkzrXs
![image](https://user-images.githubusercontent.com/30205205/58454463-25684500-80e4-11e9-8c03-5777ef7bace6.png)

**Comment by EwyBoy** [comment]
Thanks for the bug report.
The should be resolved in the next build, 2.0.3-1.12.2.
Link: https://minecraft.curseforge.com/projects/floating-rails/files/2716813
